package client

// Code generated by scripts/wire-stub-to-parent.py — exec delegate to radisson CLI (--brand).

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const wireParentSlug = "radisson"

func wireParentBin() (string, error) {
	envKey := strings.ToUpper(strings.ReplaceAll(wireParentSlug, "-", "_")) + "_BIN"
	if p := os.Getenv(envKey); p != "" {
		return p, nil
	}
	for _, rel := range []string{
		filepath.Join("..", wireParentSlug+"-cli", wireParentSlug),
		wireParentSlug,
	} {
		if st, err := os.Stat(rel); err == nil && !st.IsDir() {
			abs, _ := filepath.Abs(rel)
			return abs, nil
		}
	}
	if p, err := exec.LookPath(wireParentSlug); err == nil {
		return p, nil
	}
	return "", fmt.Errorf("parent binary %q not found — build ../%s-cli or set %s_BIN", wireParentSlug, wireParentSlug, strings.ToUpper(strings.ReplaceAll(wireParentSlug, "-", "_")))
}

// Search delegates to the radisson parent CLI with this slug's brand filter.
func (c *Client) Search(query string, page, pageSize int) (*HotelSearchResult, error) {
	brand := c.Brand
	if brand == "" {
		brand = "Leonardo Hotels"
	}
	bin, err := wireParentBin()
	if err != nil {
		return nil, err
	}
	args := []string{"search", "--json", "--brand", brand, "--limit", fmt.Sprint(pageSize), "--page", fmt.Sprint(page)}
	args = append(args, strings.Fields(query)...)
	out, err := exec.Command(bin, args...).Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok && len(ee.Stderr) > 0 {
			return nil, fmt.Errorf("%s: %s", wireParentSlug, strings.TrimSpace(string(ee.Stderr)))
		}
		return nil, fmt.Errorf("%s: %w", wireParentSlug, err)
	}
	var res HotelSearchResult
	if err := json.Unmarshal(out, &res); err != nil {
		return nil, fmt.Errorf("%s json: %w", wireParentSlug, err)
	}
	return &res, nil
}
