#!/usr/bin/env python3
"""Wire stub CLIs to a parent slug's implemented search API.

For each *-cli whose internal/client/search.go is still a scaffold stub:
  - if groups.json maps slug -> parent P and P != slug
  - and parent P has a non-stub search.go
  - replace search.go with a delegate (default: exec parent CLI binary with --brand)

Go modules cannot import another CLI's internal/client package, so the default
strategy shells out to the parent binary. Use --strategy copy-client to copy
parent client/*.go sources into the child (same package, parent's BaseURL).

Re-run after parallel agents land parent APIs. Idempotent (skips already-wired files).
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

from groups_lib import (
    ROOT,
    default_brand,
    enrich_groups,
    groups_list,
    load_groups_doc,
    parent_for_slug,
    save_groups_doc,
)

STUB_MARK = "search not yet implemented"
WIRED_MARK = "Code generated by scripts/wire-stub-to-parent.py"
SEARCH_GO = Path("internal/client/search.go")
CLIENT_GO = Path("internal/client/client.go")
GO_MOD = Path("go.mod")

HOTEL_CLIENT_FILES = ("search.go", "read.go", "availability.go")
AIRLINE_CLIENT_FILES = ("search.go", "read.go")


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def is_scaffold_stub(search_path: Path) -> bool:
    if not search_path.is_file():
        return False
    text = read_text(search_path)
    return STUB_MARK in text and WIRED_MARK not in text


def is_wired(search_path: Path) -> bool:
    return search_path.is_file() and WIRED_MARK in read_text(search_path)


def is_implemented(search_path: Path) -> bool:
    if not search_path.is_file():
        return False
    text = read_text(search_path)
    return STUB_MARK not in text and "func (c *Client) Search(" in text


def json_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def hotel_exec_delegate(parent: str, default_brand_name: str) -> str:
    env_key = parent.upper().replace("-", "_")
    return f"""package client

// {WIRED_MARK} — exec delegate to {parent} CLI (--brand).

import (
\t"encoding/json"
\t"fmt"
\t"os"
\t"os/exec"
\t"path/filepath"
\t"strings"
)

const wireParentSlug = {json_str(parent)}

func wireParentBin() (string, error) {{
\tenvKey := strings.ToUpper(strings.ReplaceAll(wireParentSlug, "-", "_")) + "_BIN"
\tif p := os.Getenv(envKey); p != "" {{
\t\treturn p, nil
\t}}
\tfor _, rel := range []string{{
\t\tfilepath.Join("..", wireParentSlug+"-cli", wireParentSlug),
\t\twireParentSlug,
\t}} {{
\t\tif st, err := os.Stat(rel); err == nil && !st.IsDir() {{
\t\t\tabs, _ := filepath.Abs(rel)
\t\t\treturn abs, nil
\t\t}}
\t}}
\tif p, err := exec.LookPath(wireParentSlug); err == nil {{
\t\treturn p, nil
\t}}
\treturn "", fmt.Errorf("parent binary %q not found — build ../%s-cli or set %s_BIN", wireParentSlug, wireParentSlug, strings.ToUpper(strings.ReplaceAll(wireParentSlug, "-", "_")))
}}

// Search delegates to the {parent} parent CLI with this slug's brand filter.
func (c *Client) Search(query string, page, pageSize int) (*HotelSearchResult, error) {{
\tbrand := c.Brand
\tif brand == "" {{
\t\tbrand = {json_str(default_brand_name)}
\t}}
\tbin, err := wireParentBin()
\tif err != nil {{
\t\treturn nil, err
\t}}
\targs := []string{{"search", "--json", "--brand", brand, "--limit", fmt.Sprint(pageSize), "--page", fmt.Sprint(page)}}
\targs = append(args, strings.Fields(query)...)
\tout, err := exec.Command(bin, args...).Output()
\tif err != nil {{
\t\tif ee, ok := err.(*exec.ExitError); ok && len(ee.Stderr) > 0 {{
\t\t\treturn nil, fmt.Errorf("%s: %s", wireParentSlug, strings.TrimSpace(string(ee.Stderr)))
\t\t}}
\t\treturn nil, fmt.Errorf("%s: %w", wireParentSlug, err)
\t}}
\tvar res HotelSearchResult
\tif err := json.Unmarshal(out, &res); err != nil {{
\t\treturn nil, fmt.Errorf("%s json: %w", wireParentSlug, err)
\t}}
\treturn &res, nil
}}
"""


def airline_exec_delegate(parent: str, default_brand_name: str) -> str:
    return f"""package client

// {WIRED_MARK} — exec delegate to {parent} CLI (--brand).

import (
\t"encoding/json"
\t"fmt"
\t"os"
\t"os/exec"
\t"path/filepath"
\t"strings"
)

const wireParentSlug = {json_str(parent)}

func wireParentBin() (string, error) {{
\tenvKey := strings.ToUpper(strings.ReplaceAll(wireParentSlug, "-", "_")) + "_BIN"
\tif p := os.Getenv(envKey); p != "" {{
\t\treturn p, nil
\t}}
\tfor _, rel := range []string{{
\t\tfilepath.Join("..", wireParentSlug+"-cli", wireParentSlug),
\t\twireParentSlug,
\t}} {{
\t\tif st, err := os.Stat(rel); err == nil && !st.IsDir() {{
\t\t\tabs, _ := filepath.Abs(rel)
\t\t\treturn abs, nil
\t\t}}
\t}}
\tif p, err := exec.LookPath(wireParentSlug); err == nil {{
\t\treturn p, nil
\t}}
\treturn "", fmt.Errorf("parent binary %q not found — build ../%s-cli or set %s_BIN", wireParentSlug, wireParentSlug, strings.ToUpper(strings.ReplaceAll(wireParentSlug, "-", "_")))
}}

// Search delegates to the {parent} parent CLI with this slug's brand filter.
func (c *Client) Search(origin, dest, depart, ret string, page, pageSize int) (*FlightSearchResult, error) {{
\tbrand := c.Brand
\tif brand == "" {{
\t\tbrand = {json_str(default_brand_name)}
\t}}
\tbin, err := wireParentBin()
\tif err != nil {{
\t\treturn nil, err
\t}}
\targs := []string{{"search", "--json", "--brand", brand, "--from", origin, "--to", dest, "--depart", depart, "--limit", fmt.Sprint(pageSize), "--page", fmt.Sprint(page)}}
\tif ret != "" {{
\t\targs = append(args, "--return", ret)
\t}}
\tout, err := exec.Command(bin, args...).Output()
\tif err != nil {{
\t\tif ee, ok := err.(*exec.ExitError); ok && len(ee.Stderr) > 0 {{
\t\t\treturn nil, fmt.Errorf("%s: %s", wireParentSlug, strings.TrimSpace(string(ee.Stderr)))
\t\t}}
\t\treturn nil, fmt.Errorf("%s: %w", wireParentSlug, err)
\t}}
\tvar res FlightSearchResult
\tif err := json.Unmarshal(out, &res); err != nil {{
\t\treturn nil, fmt.Errorf("%s json: %w", wireParentSlug, err)
\t}}
\treturn &res, nil
}}
"""


def parent_base_url(parent: str) -> str | None:
    text = read_text(ROOT / f"{parent}-cli" / CLIENT_GO)
    m = re.search(r'const BaseURL = "([^"]+)"', text)
    return m.group(1) if m else None


def patch_child_base_url(cli_dir: Path, parent: str) -> None:
    url = parent_base_url(parent)
    if not url:
        return
    path = cli_dir / CLIENT_GO
    text = read_text(path)
    text = re.sub(r'const BaseURL = "[^"]+"', f'const BaseURL = "{url}"', text, count=1)
    path.write_text(text, encoding="utf-8")


def copy_parent_client_files(cli_dir: Path, parent: str, cat: str) -> None:
    names = HOTEL_CLIENT_FILES if cat == "hotel" else AIRLINE_CLIENT_FILES
    parent_dir = ROOT / f"{parent}-cli/internal/client"
    child_dir = cli_dir / "internal/client"
    for name in names:
        src = parent_dir / name
        if not src.is_file():
            continue
        body = read_text(src)
        if body.startswith("// " + WIRED_MARK):
            body = body.split("\n", 1)[1]
        header = f"// {WIRED_MARK} — copied from {parent}-cli/{name}\n"
        (child_dir / name).write_text(header + body, encoding="utf-8")
    patch_child_base_url(cli_dir, parent)


def remove_parent_go_mod_refs(go_mod_path: Path, parent: str) -> None:
    if not go_mod_path.is_file():
        return
    text = read_text(go_mod_path)
    module = f"github.com/fbelchi/{parent}-cli"
    lines = [
        ln
        for ln in text.splitlines()
        if module not in ln or "replace" in ln and "travelkit" in ln
    ]
    # also drop replace for parent
    lines = [ln for ln in lines if f"replace {module}" not in ln]
    go_mod_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def should_wire(search_path: Path, force: bool) -> bool:
    if is_scaffold_stub(search_path):
        return True
    return force and is_wired(search_path)


def wire_slug(
    slug: str,
    parent: str,
    cat: str,
    brand_name: str,
    dry_run: bool,
    force: bool,
    strategy: str,
) -> bool:
    cli_dir = ROOT / f"{slug}-cli"
    search_path = cli_dir / SEARCH_GO
    if not should_wire(search_path, force):
        return False
    parent_search = ROOT / f"{parent}-cli" / SEARCH_GO
    if not is_implemented(parent_search):
        return False
    if slug == parent:
        return False

    if dry_run:
        print(f"would wire {slug} -> {parent} ({cat}, {strategy})")
        return True

    if strategy == "copy-client":
        copy_parent_client_files(cli_dir, parent, cat)
        remove_parent_go_mod_refs(cli_dir / GO_MOD, parent)
    else:
        content = (
            hotel_exec_delegate(parent, brand_name)
            if cat == "hotel"
            else airline_exec_delegate(parent, brand_name)
        )
        search_path.write_text(content, encoding="utf-8")
        remove_parent_go_mod_refs(cli_dir / GO_MOD, parent)

    print(f"wired {slug} -> {parent} ({strategy})")
    return True


def count_stubs() -> int:
    return sum(1 for d in ROOT.glob("*-cli") if is_scaffold_stub(d / SEARCH_GO))


def verify_build(slugs: list[str]) -> tuple[int, int]:
    ok = fail = 0
    for slug in slugs:
        cli_dir = ROOT / f"{slug}-cli"
        r = subprocess.run(
            ["go", "build", "-o", slug, f"./cmd/{slug}"],
            cwd=cli_dir,
            capture_output=True,
            text=True,
        )
        if r.returncode == 0:
            ok += 1
            (cli_dir / slug).unlink(missing_ok=True)
        else:
            fail += 1
            print(f"BUILD FAIL {slug}: {r.stderr.strip()[:300]}", file=sys.stderr)
    return ok, fail


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--dry-run", action="store_true", help="print actions only")
    ap.add_argument("--verify", action="store_true", help="go build wired slugs")
    ap.add_argument("--sync-groups", action="store_true", help="refresh groups.json parent maps")
    ap.add_argument("--force", action="store_true", help="re-wire files already marked wired")
    ap.add_argument(
        "--strategy",
        choices=("exec", "copy-client"),
        default="exec",
        help="exec parent CLI (default) or copy parent client/*.go sources",
    )
    args = ap.parse_args()

    doc = enrich_groups(load_groups_doc())
    if args.sync_groups or (not args.dry_run and not args.force):
        save_groups_doc(doc)

    stubs_before = count_stubs()
    wired: list[str] = []

    for g in groups_list(doc):
        slug = g["slug"]
        parent = parent_for_slug(slug, doc)
        if wire_slug(slug, parent, g["cat"], default_brand(g), args.dry_run, args.force, args.strategy):
            wired.append(slug)

    stubs_after = count_stubs() if not args.dry_run else stubs_before - len(wired)

    brands_delegated = sorted(
        {
            b
            for g in groups_list(doc)
            for b in g["brands"]
            if parent_for_slug(g["slug"], doc) != g["slug"]
            and g["slug"] in wired
        }
    )

    print(f"stubs_before={stubs_before}")
    print(f"stubs_after={stubs_after}")
    print(f"wired_count={len(wired)}")
    if wired:
        print("wired_slugs=" + ",".join(wired))
    print(f"brands_delegated={len(brands_delegated)}")

    if args.verify and wired and not args.dry_run:
        for slug in wired:
            cli_dir = ROOT / f"{slug}-cli"
            subprocess.run(["go", "mod", "tidy"], cwd=cli_dir, check=False)
        ok, fail = verify_build(wired)
        print(f"build_ok={ok} build_fail={fail}")
        return 1 if fail else 0

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
